localaddr = ":7777"
proxyaddr = ":7778"

[tls]
type = "minivault"
initialtimeout = "1h"
[tls.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dc2a69fa781e6cf.c89679768a0c16f5"
tokentype = "server_cert"
tokenpolicies = ["miniresolver"]
tokeninterval = "1h"
tokenttl = "2h"
certtype = "server_cert"
dnss = ["localhost"]
uris = []
ips = ["127.0.0.1", "::1"]
certinterval = "8m"
certttl = "10m"
ca = ["""-----BEGIN CERTIFICATE-----
MIICxTCCAkqgAwIBAgIGAY4FTF/mMAoGCCqGSM49BAMDMIGYMQswCQYDVQQGEwJD
SDETMBEGA1UECBMKQmFzZWwgQ2l0eTEOMAwGA1UEBxMFQmFzZWwxIDAeBgNVBAkM
F1NjaMO2bmJlaW5zdHJhc3NlIDE4LTIwMQ0wCwYDVQQREwQ0MDU2MSEwHwYDVQQK
ExhVbml2ZXJzaXR5IExpYnJhcnkgQmFzZWwxEDAOBgNVBAMTB0R1bW15Q0EwHhcN
MjQwMzAzMTcxMTE1WhcNMzQwMzAxMTcxMTE1WjCBmDELMAkGA1UEBhMCQ0gxEzAR
BgNVBAgTCkJhc2VsIENpdHkxDjAMBgNVBAcTBUJhc2VsMSAwHgYDVQQJDBdTY2jD
tm5iZWluc3RyYXNzZSAxOC0yMDENMAsGA1UEERMENDA1NjEhMB8GA1UEChMYVW5p
dmVyc2l0eSBMaWJyYXJ5IEJhc2VsMRAwDgYDVQQDEwdEdW1teUNBMHYwEAYHKoZI
zj0CAQYFK4EEACIDYgAErHxZYoHwHzTqRg14Ve9/APs/D+sMSKDTpPTZYFocZedF
VGJEkeaCqQvsCY5G9WaHXI7jZtewKo/bHM/WcmXZB+cZNmJn/IyBHJAYh5xN5WBY
vUPJfRfQosSFr8SDE4MPo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYI
KwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFH+I
PuzNyAOrQ+rMTtywGqm3Z5ARMAoGCCqGSM49BAMDA2kAMGYCMQDJNau3j1v1FQHQ
n7kn+gEATGOm+9fBsgUCGXmKvLZPIJI3NI2URLmlmASdEIrg/N4CMQCNQio9BHom
JYLotIXmdUEmKuXZeKoc0eR1jA7kWdJNOvEpE73mx/zutDeNl3hRVP0=
-----END CERTIFICATE-----
"""]
usesystempool = false

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="miniresolver"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"

